import type {
	AgentDef,
	BuildContext,
	OutputFile,
	ToolAdapter,
} from "@sdlc-agents/core";

export class CopilotAdapter implements ToolAdapter {
	readonly name = "copilot";

	render(agents: AgentDef[], _ctx: BuildContext): OutputFile[] {
		return [
			{
				path: ".github/copilot-instructions.md",
				content: this.renderInstructions(agents),
			},
			...agents.map((a) => ({
				path: `.github/prompts/${a.id}.prompt.md`,
				content: this.renderPrompt(a),
			})),
		];
	}

	private renderInstructions(agents: AgentDef[]): string {
		const agentRefs = agents
			.map(
				(a) =>
					`- **${a.id}** (phase: ${a.phase}) — ${firstLine(a.description)}\n` +
					`  Prompt: [.github/prompts/${a.id}.prompt.md](.github/prompts/${a.id}.prompt.md)`,
			)
			.join("\n\n");

		return `# SDLC Agents — Copilot Instructions

This repository uses the **Agentic SDLC Agents Set**. Activate an agent by opening
its prompt file or asking Copilot Chat: _"@workspace follow the ${agents[0]?.id ?? "planner"} agent workflow"_.

## Available Agents

${agentRefs}

---
_Generated by sdlc-agents. Run \`sdlc build\` to regenerate._
`;
	}

	private renderPrompt(agent: AgentDef): string {
		const inputs = agent.inputs.length
			? agent.inputs
					.map(
						(i) =>
							`- **${i.name}**${i.required ? " (required)" : ""}: ${i.description ?? ""}`,
					)
					.join("\n")
			: "_None_";

		const workflow = agent.workflow
			.map((w, i) => `${i + 1}. ${w.step}`)
			.join("\n");

		const copilotNote = agent.model_variants?.copilot?.prompt_append
			? `\n> **Copilot note:** ${agent.model_variants.copilot.prompt_append}\n`
			: "";

		return `---
mode: agent
description: "${firstLine(agent.description)}"
---

# ${agent.id} (phase: ${agent.phase})

${agent.description.trim()}
${copilotNote}
## Inputs

${inputs}

## Workflow

${workflow}
${agent.output_template ? `\n## Output\n\nUse template \`${agent.output_template}\`.\n` : ""}
---
_Generated by sdlc-agents. Do not edit — run \`sdlc build\` to regenerate._
`;
	}
}

function firstLine(text: string): string {
	return text.trim().split("\n")[0] ?? text.trim();
}
