import type {
	AgentDef,
	BuildContext,
	OutputFile,
	ToolAdapter,
} from "@sdlc-agents/core";

export class UniversalAdapter implements ToolAdapter {
	readonly name = "universal";

	render(agents: AgentDef[], _ctx: BuildContext): OutputFile[] {
		return [
			{ path: "AGENTS.md", content: this.renderIndex(agents) },
			...agents.map((a) => ({
				path: `.sdlc/agents/${a.id}.md`,
				content: this.renderAgent(a),
			})),
		];
	}

	private renderIndex(agents: AgentDef[]): string {
		const rows = agents
			.map(
				(a) =>
					`| [\`${a.id}\`](.sdlc/agents/${a.id}.md) | ${a.phase} | ${firstLine(a.description)} |`,
			)
			.join("\n");

		return `# SDLC Agents

This project uses the **Agentic SDLC Agents Set** — AI agents for every SDLC phase.

## How to invoke

- **Claude Code / Cursor / Windsurf / Codex / Gemini CLI:** name the agent explicitly,
  e.g. _"use the \`planner\` agent to break down this spec"_
- **All tools:** open the agent file under \`.sdlc/agents/\` and follow the workflow

## Available Agents

| Agent | Phase | Description |
|-------|-------|-------------|
${rows}

---
_Generated by sdlc-agents. Run \`sdlc build\` to regenerate._
`;
	}

	private renderAgent(agent: AgentDef): string {
		const inputs = agent.inputs.length
			? agent.inputs
					.map(
						(i) =>
							`- **${i.name}**${i.required ? " *(required)*" : ""}: ${i.description ?? ""}`,
					)
					.join("\n")
			: "_None_";

		const workflow = agent.workflow
			.map((w, i) => `${i + 1}. ${w.step}${w.ref ? ` (see \`${w.ref}\`)` : ""}`)
			.join("\n");

		const policies = agent.policies.length
			? agent.policies
					.map((p) => `- [\`${p}\`](../../policies/${p}.md)`)
					.join("\n")
			: "";

		return `# ${agent.id}

**Phase:** ${agent.phase} | **Version:** ${agent.version} | **Model:** ${agent.model_hint}

## What this agent does

${agent.description.trim()}

## Inputs

${inputs}

## Workflow

${workflow}
${agent.output_template ? `\n## Output\n\nUse template \`${agent.output_template}\`.\n` : ""}${policies ? `\n## Policies\n\n${policies}\n` : ""}
---
_Generated by sdlc-agents. Universal tier — works on any AI tool. Run \`sdlc build\` to regenerate._
`;
	}
}

function firstLine(text: string): string {
	return text.trim().split("\n")[0] ?? text.trim();
}
